---
# tasks file for postfix
- name: postfix install
  package:
    name: postfix
    state: latest
  register: result
  until: result is success
  retries: 3
  delay: 5

- name: create Maildir for root
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0700
    state: directory
  with_items:
    - /root/Maildir
    - /root/Maildir/new
    - /root/Maildir/cur
    - /root/Maildir/tmp
    - /etc/skel/Maildir
    - /etc/skel/Maildir/new
    - /etc/skel/Maildir/cur
    - /etc/skel/Maildir/tmp

- block:
  - name: postfix setting
    template:
      src: main.cf.j2
      dest: /etc/postfix/main.cf
      owner: root
      group: root
      mode: 0644
      backup: yes
    register: is_main_cf_setting
    notify: postfix restart

  always:
  - name: postfix backup settings
    include_tasks: backup.yml
    with_flattened:
      - "{{ is_main_cf_setting|default() }}"
    loop_control:
      loop_var: backup_item

- name: postfix enable
  service:
    name: postfix
    state: started
    enabled: yes
    daemon_reload: yes
